"""
title: Text to Cypher Pipeline
author: 0xThresh
date: 2025-02-10
version: 1.1
license: MIT
description: A pipeline for using text-to-Cypher for retrieving relevant information from a
Graph database using the Langchain library.
requirements: langchain, sqlalchemy, psycopg2-binary
"""

from typing import List, Union, Generator, Iterator
import os

from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel
from langchain_ollama import ChatOllama
from langchain_neo4j import GraphCypherQAChain
from langchain_neo4j import Neo4jGraph


class Pipeline:
    class Valves(BaseModel):
        DB_HOST: str
        DB_PORT: str
        DB_USER: str
        DB_PASSWORD: str
        DB_DATABASE: str
        # DB_TABLE: str
        OLLAMA_HOST: str
        TEXT_TO_CYPHER_MODEL: str

    # Update valves/ environment variables based on your selected database
    def __init__(self):
        self.name = "Neo4j Database Query Pipeline with Query shown"
        self.graph = None
        self.nlsql_response = ""
        print("init done")

        # Initialize
        self.valves = self.Valves(
            **{
                "pipelines": ["*"],
                "DB_HOST": os.getenv("DB_HOST", "neo4j"),
                "DB_PORT": os.getenv("DB_PORT", "7687"),
                "DB_USER": os.getenv("DB_USER", "neo4j"),
                "DB_PASSWORD": os.getenv("DB_PASSWORD", "neo4j123"),
                "DB_DATABASE": os.getenv("DB_DATABASE", "neo4j"),
                # "DB_TABLE": os.getenv("DB_TABLE", "product"),
                "OLLAMA_HOST": os.getenv("OLLAMA_HOST", "http://ollama:11434"),
                "TEXT_TO_CYPHER_MODEL": os.getenv("TEXT_TO_CYPHER_MODEL", "mistral:latest")
            }
        )

    def init_graph_connection(self):
        self.graph = Neo4jGraph(
            url=f"neo4j://{self.valves.DB_HOST}:{self.valves.DB_PORT}",
            username=self.valves.DB_USER,
            password=self.valves.DB_PASSWORD,
            database=self.valves.DB_DATABASE,
            enhanced_schema=True
        )
        self.graph.refresh_schema()
        print("Neo4j connection initialized")
        return self.graph

    async def on_startup(self):
        # This function is called when the server is started.
        print("on_startup")
        self.init_graph_connection()

    async def on_shutdown(self):
        # This function is called when the server is stopped.
        print("on_shutdown")
        pass

    def pipe(
            self, user_message: str, model_id: str, messages: List[dict], body: dict
    ) -> Union[str, Generator, Iterator]:
        # Debug logging is required to see what SQL query is generated by the LlamaIndex library; enable on Pipelines server if needed

        if self.graph is None:
            self.init_graph_connection()

        # Set up LLM connection; uses phi3 model with 128k context limit since some queries have returned 20k+ tokens
        print("setting up llm")
        print(self.valves.OLLAMA_HOST)
        llm = ChatOllama(
            model=self.valves.TEXT_TO_CYPHER_MODEL, base_url=self.valves.OLLAMA_HOST, temperature=0)

        # Set up the custom prompt used when generating SQL queries from text
        text_to_cypher_prompt = """
        Given an input question, generate a syntactically correct Cypher query to retrieve the relevant information from the Neo4j database. 
        Then, execute the query and return the answer based on the results.

        - Prioritize relationships and connections between nodes when forming the query.

        - Avoid querying all properties of a node; only retrieve the most relevant attributes based on the question.
        - Use `DISTINCT` to eliminate duplicate results whenever applicable.
        - Ensure all node labels and relationship types match those found in the schema.
        - Always qualify property names with their corresponding node labels if needed.
        - Show always the Cypher query you used.
        - You must use the following structured format, with each part on a separate line:

        Question: {query}  
        CypherQuery: Generated Cypher query  
        CypherResult: Result of the CypherQuery  
        Answer: Final natural language answer

        Use only the nodes and relationships from the schema below:  
        {schema}

        Question: {query}  
        CypherQuery:
        """

        text_to_cypher_template = PromptTemplate(template=text_to_cypher_prompt,
                                                 input_variables=["query", "schema"])

        input_data = {
            "query": user_message,  # Pass the user message as query_str
            "schema": self.graph.schema  # Use the graph schema for 'schema'
        }

        query_engine = GraphCypherQAChain.from_llm(
            llm, graph=self.graph, verbose=True,
            return_intermediate_steps=True,
            allow_dangerous_requests=True,
            validate_cypher=True,
            cypher_prompt=text_to_cypher_template,
            use_function_response=True,
            top_k=50,
        )

        response = query_engine.invoke(input_data)

        if response is None:
            print("Error: query_engine.invoke() returned None.")

        query_printed = response['intermediate_steps']
        answer_printed = response['result']

        combined_string = f"{query_printed}\n{answer_printed}"

        return combined_string



# def main():
#     pipeline = Pipeline()
#     pipeline.init_graph_connection()
#
#     print(
#         "LangChain Graph Pipeline. Type 'exit' to quit.")
#     while True:
#         user_message = input("Enter your query: ")
#         if user_message.lower() == "exit":
#             break
#
#         response = pipeline.pipe(
#             user_message=user_message,
#             model_id="qwen2.5:7b",
#             # Example model ID
#             messages=[],
#             # Empty list if no prior conversation context
#             body={}
#             # Empty dict if no additional request metadata
#         )
#
#         print("\nResponse:")
#         for chunk in response:
#             print(chunk, end="")
#         print("\n")
#
#
# if __name__ == "__main__":
#     main()
